config/routes.rb
Rails.application.routes.draw do
  get 'products/new'

  get 'products/index'

  get 'products/edit'

  get 'products/delete'

  get 'products/drop'

  get 'users/new'

  get 'users/index'

  get 'users/edit'

  get 'users/delete'

  get 'users/drop'

  resources :users do 
  	collection do 
       get 'sign_in'
       post 'signup'
       delete 'logout'
  	end
  end
  root to: "users#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>", small: "200x200>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
	belongs_to :user
end

app/models/ipl.rb
class Ipl < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password , presence: true
  validates :confirm_password , presence: true
  validates :mobile, presence: true, numericality: true
  has_one :image 
  accepts_nested_attributes_for :image
    before_save :encrypt_password
    before_save :check_name
    before_validation :verify_password
def check_name
  if name.blank?
    self.name="unknow"
  end
end
    def encrypt_password
       self.password = Digest::MD5.hexdigest(password)
       self.confirm_password = Digest::MD5.hexdigest(confirm_password)
    end
    def verify_password
      if password != confirm_password
           errors.add(:base, "password & confirm_password are not equal!" )
      end
    end
  def self.authenticate(email, password)
    if @user = User.where(email: email, password: Digest::MD5.hexdigest(password)).last
           @user
       else
        nil
       end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user

  def authenticate_user
     if session[:user_id].blank?
         redirect_to sign_in_users_path
     end
  end
end

app/controllers/mani_controller.rb
class ManiController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
  end

  def index
  end

  def edit
  end

  def delete
  end

  def drop
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: [:sign_in, :signup, :new, :create]
  def index
    @users =  User.all
  end

  def new
    @user = User.new
    @user.build_image
  end
  def create 
    @user = User.new(user_params)
    if @user.save(validate: false)
        UserMailer.signup_conformation(@user).deliver_now
       redirect_to users_path
   else
    render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end
  def update
    @user = User.find params[:id]
    if @user.update(user_params)
       redirect_to users_path
       else
       render :edit 
    end
  end 
  def show
    @user = User.find params[:id]
  end
  def destroy 
     @user = User.find params[:id]
     @user.destroy
     redirect_to users_path
  end
  def signup
      @user = User.authenticate(params[:email], params[:password])
      if @user
          session[:user_id] = @user.id
          flash[:notice] = "Successfully logged in!"
          redirect_to users_path
        else
          flash[:notice] = "Either email or password is wrong!"
          redirect_to sign_in_users_path
      end
  end
  def logout
    session[:user_id] = nil
    redirect_to sign_in_users_path
  end
  private 
  def user_params
    params.require(:user).permit!
  end
end

app/controllers/vikki_controller.rb
class VikkiController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mani_helper.rb
module ManiHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vikki_helper.rb
module VikkiHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gaming</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% unless session[:user_id].nil?%>
  <%= link_to "Logout", logout_users_path, method: :delete%>
  <%end%>
  <% flash.each do |_, value|%>
    <%= value%>
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/products/delete.html.erb
<h1>Products#delete</h1>
<p>Find me in app/views/products/delete.html.erb</p>

app/views/products/drop.html.erb
<h1>Products#drop</h1>
<p>Find me in app/views/products/drop.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/users/edit.html.erb
<%= form_for @user do |f|%>
<table>
  <tr>
  <td><%= f.label :name%></td>
  <td><%= f.text_field :name%></td>
  </tr>
  <tr>
  <td><%= f.label :email%></td>
  <td><%= f.email_field :email%></td>
  </tr>
  <tr>
  <td><%= f.label :mobile%></td>
  <td><%= f.text_field :mobile%></td>
  </tr>
  <tr>
  <td><%= f.label :status%></td>
  <td><%= f.check_box :status%></td>
  </tr>
    <tr>
  <td><%= f.submit "Save"%></td>
  </tr>
</table>
<%end%>

<%= link_to "<<back", users_path%>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<!--%= @users.inspect %-->

<table>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Mobile</th>
		<th>Status</th>
		</tr>

	<tr>  
      <td><%= @user.name %></td>
      <td><%= @user.email %></td>
      <td><%= @user.mobile %></td>
      <td><%= @user.status %></td>
      <td><%= link_to "Show", user_path(@user)%>
      <td><%= link_to "Edit", edit_user_path(@user)%></td>
      <td><%= link_to "Delete", @user, method: :delete, data: {confirm: "Are you sure!"}%></td>
	</tr>

</table>

<%= link_to "Add New User", new_user_path%>

app/views/users/sign_in.html.erb
<%= form_tag action: :signup, method: :post do%>
<table  class="table table-striped">
  <tr>
  <td><%= label_tag :email%></td>
  <td><%= email_field_tag :email%></td>
  </tr>
  <tr>
  <td><%= label_tag :password%></td>
  <td><%= password_field_tag :password%></td>
  </tr>
   <tr>
  <td><%= submit_tag "SignIn"%></td>
  <td><%= link_to "SignUp", new_user_path%></td>
  </tr>
</table>
<%end%>

app/views/vikki/edit.html.erb
<h1>Vikki#edit</h1>
<p>Find me in app/views/vikki/edit.html.erb</p>

app/views/vikki/index.html.erb
<h1>Vikki#index</h1>
<p>Find me in app/views/vikki/index.html.erb</p>

app/views/vikki/new.html.erb
<h1>Vikki#new</h1>
<p>Find me in app/views/vikki/new.html.erb</p>

app/views/vikki/show.html.erb
<h1>Vikki#show</h1>
<p>Find me in app/views/vikki/show.html.erb</p>